### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by ayvazj** [halvves/zazu-giphy#6]
I installed the plugin by updating my my config file, reloaded the config, restarted zazu, and the giphy plugin still does not work as illustrated in the readme.

My ~/.zazurc.json

```
  {
    "hotkey": "alt+space",
    "theme": "tinytacoteam/zazu-dark-theme",
    "displayOn": "detect",
    "plugins": [
      "halvves/zazu-giphy",
      "tinytacoteam/zazu-calculator",
      "tinytacoteam/zazu-file-finder",
      "tinytacoteam/zazu-template",
      "tinytacoteam/zazu-system",
      "tinytacoteam/zazu-package-manager",
      {
        "name": "tinytacoteam/zazu-fallback",
        "variables": {
          "rootSearches": [
            "google"
          ]
        }
      },
      {
        "name": "tinytacoteam/zazu-clipboard",
        "variables": {
          "ClipboardKey": "cmd+shift+v"
        }
      }
    ]
  }
```

**Comment by mmmerl** [comment]
hey! it looks like giphy finally got rid of their demo api key in favor of individual app demo keys. it also looks like the rate limit on the app demo keys isn't the greatest. i could apply for a production key, but really don't like that there is no easy way for me to avoid having to keep that somewhere in the code. what i'm currently thinking is updating this plugin to be more of a bring your own key situation (like how some of the diy slack integrations work). you'd need to have a giphy account and create your own api key which you would then add to your `zazurc.json` like so:

```
{
  "name": "halvves/zazu-giphy"
  "variables": {
    "api_key": "xxxxxxxxxxxxxx"
  }
}
```

how does this sound to you?

**Comment by ayvazj** [comment]
👍 works for me and a good long term solution.

**Comment by mmmerl** [comment]
so i finally started to take a stab at this, and it turns out the giphy demo api is still chugging along (results are being fetched and i can copy and paste giphy links by actioning them). the actual problem is some changes to zazu's preview handling in [this commit](https://github.com/tinytacoteam/zazu/commit/afb090547a7ecc0e5dc34e58403f685b67f0435a#diff-2718248ecf9b3814c6e7fa23feb0a024). i'll have to find a workaround to make previews work again and file an issue with zazu, because this way of handling previews makes it a huge pain for plugin authors.

**Comment by mmmerl** [comment]
rip zazu 😢🙏🪦
